---
- hosts: all
  vars:
      app_name: "fingram"
      app_repo: "spolikarpov/fingram:latest"
      app_folder: "~/fingram"
      vars_folder: /opt/fingram/vars
      local_vars: "{{ lookup('env','FINGRAM_LOCAL_VARS') }}"
      local_secret: "{{ lookup('env','FINGRAM_ACC_SECRET') }}"
  become: yes
  tasks:
        - name: Create application folder
          file:
            path: '{{ app_folder }}'
            state: directory

        - name: Upload correct variable file and key
          template: src={{item.src}} dest={{item.dest}}
          with_items:
              - { src: '{{ local_vars }}', dest: '{{ app_folder }}/variables.json' }
              - { src: '{{ local_secret }}', dest: '{{ app_folder }}/{{ local_secret }}' }

        - name: Run fingram docker container
          shell: cd {{ app_folder }} && docker run -d --rm --name {{ app_name }} -v $(pwd):{{ vars_folder }} {{ app_repo }}
